"""Initial schema: users/roles, documents + pgvector chunks, research domain,
agent run audit trail, approvals and the evaluation dataset.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-18 15:59:52.265794
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Extensions first: document_chunks.embedding needs `vector`, compound name
    # lookup uses trigram similarity, and UUID defaults need pgcrypto. Compose
    # seeds these via init.sql, but a fresh RDS instance has none - so the
    # migration owns them and `alembic upgrade head` is sufficient anywhere.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "compounds",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("iupac_name", sa.String(length=512), nullable=True),
        sa.Column("smiles", sa.String(length=1024), nullable=True),
        sa.Column("molecular_weight", sa.Float(), nullable=True),
        sa.Column("mechanism_of_action", sa.Text(), nullable=True),
        sa.Column("therapeutic_area", sa.String(length=128), nullable=True),
        sa.Column("development_phase", sa.String(length=64), nullable=True),
        sa.Column("targets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "molecular_weight IS NULL OR molecular_weight > 0",
            name=op.f("ck_compounds_molecular_weight_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compounds")),
        sa.UniqueConstraint("code", name="uq_compounds_code"),
    )
    op.create_index(op.f("ix_compounds_created_at"), "compounds", ["created_at"], unique=False)
    op.create_index(op.f("ix_compounds_name"), "compounds", ["name"], unique=False)
    op.create_index(
        "ix_compounds_name_area", "compounds", ["name", "therapeutic_area"], unique=False
    )
    op.create_index(
        op.f("ix_compounds_therapeutic_area"), "compounds", ["therapeutic_area"], unique=False
    )
    op.create_table(
        "evaluation_cases",
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("suite", sa.String(length=64), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("expected_behavior", sa.Text(), nullable=False),
        sa.Column("expected_category", sa.String(length=32), nullable=True),
        sa.Column("expected_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("forbidden_tools", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "expected_tool_arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "expected_evidence_keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "expected_answer_keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "forbidden_answer_keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("requires_citations", sa.Boolean(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("max_latency_ms", sa.Integer(), nullable=True),
        sa.Column("max_cost_usd", sa.Float(), nullable=True),
        sa.Column("as_role", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_cases")),
        sa.UniqueConstraint("slug", name="uq_evaluation_cases_slug"),
    )
    op.create_index(
        op.f("ix_evaluation_cases_created_at"), "evaluation_cases", ["created_at"], unique=False
    )
    op.create_index(
        "ix_evaluation_cases_suite_enabled", "evaluation_cases", ["suite", "enabled"], unique=False
    )
    op.create_table(
        "research_topics",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("research_area", sa.String(length=128), nullable=False),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_topics")),
        sa.UniqueConstraint("slug", name="uq_research_topics_slug"),
    )
    op.create_index(
        op.f("ix_research_topics_created_at"), "research_topics", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_research_topics_research_area"), "research_topics", ["research_area"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_index(op.f("ix_roles_created_at"), "roles", ["created_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("department", sa.String(length=128), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_active_email", "users", ["is_active", "email"], unique=False)
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_table(
        "agent_runs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "AWAITING_APPROVAL",
                "COMPLETED",
                "FAILED",
                "REJECTED",
                "BUDGET_EXCEEDED",
                name="agentrunstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=32), nullable=True),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("final_answer", sa.Text(), nullable=True),
        sa.Column("answer_confidence", sa.String(length=16), nullable=True),
        sa.Column("answer_citations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answer_caveats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verification", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("tool_calls_used", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("llm_latency_ms", sa.Integer(), nullable=False),
        sa.Column("tool_latency_ms", sa.Integer(), nullable=False),
        sa.Column("total_latency_ms", sa.Integer(), nullable=False),
        sa.Column("models_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("iterations >= 0", name=op.f("ck_agent_runs_iterations_non_negative")),
        sa.CheckConstraint(
            "tool_calls_used >= 0", name=op.f("ck_agent_runs_tool_calls_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_agent_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(op.f("ix_agent_runs_created_at"), "agent_runs", ["created_at"], unique=False)
    op.create_index(
        "ix_agent_runs_status_created_at", "agent_runs", ["status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_agent_runs_thread_id"), "agent_runs", ["thread_id"], unique=False)
    op.create_index(
        "ix_agent_runs_user_id_created_at", "agent_runs", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "clinical_trials",
        sa.Column("registry_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("condition", sa.String(length=255), nullable=False),
        sa.Column("intervention", sa.String(length=512), nullable=True),
        sa.Column(
            "phase",
            sa.Enum(
                "PHASE_1",
                "PHASE_2",
                "PHASE_3",
                "PHASE_4",
                "NA",
                name="trialphase",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "RECRUITING",
                "ACTIVE",
                "COMPLETED",
                "TERMINATED",
                "WITHDRAWN",
                name="trialstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("sponsor", sa.String(length=255), nullable=True),
        sa.Column("enrollment", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("completion_date", sa.Date(), nullable=True),
        sa.Column("primary_outcome", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("locations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("compound_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "enrollment IS NULL OR enrollment >= 0",
            name=op.f("ck_clinical_trials_enrollment_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["compound_id"],
            ["compounds.id"],
            name=op.f("fk_clinical_trials_compound_id_compounds"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinical_trials")),
        sa.UniqueConstraint("registry_id", name="uq_clinical_trials_registry_id"),
    )
    op.create_index(
        op.f("ix_clinical_trials_compound_id"), "clinical_trials", ["compound_id"], unique=False
    )
    op.create_index(
        op.f("ix_clinical_trials_condition"), "clinical_trials", ["condition"], unique=False
    )
    op.create_index(
        "ix_clinical_trials_condition_phase",
        "clinical_trials",
        ["condition", "phase"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clinical_trials_created_at"), "clinical_trials", ["created_at"], unique=False
    )
    op.create_index(
        "ix_clinical_trials_status_start_date",
        "clinical_trials",
        ["status", "start_date"],
        unique=False,
    )
    op.create_table(
        "documents",
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "PAPER",
                "PREPRINT",
                "REVIEW",
                "CLINICAL_REPORT",
                "INTERNAL_REPORT",
                "PROTOCOL",
                name="documenttype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "access_level",
            sa.Enum(
                "PUBLIC", "INTERNAL", "RESTRICTED", name="accesslevel", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("doi", sa.String(length=255), nullable=True),
        sa.Column("journal", sa.String(length=255), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column("research_area", sa.String(length=128), nullable=True),
        sa.Column("abstract", sa.Text(), nullable=True),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ingestion_status",
            sa.Enum(
                "UPLOADED",
                "PROCESSING",
                "EXTRACTED",
                "CHUNKED",
                "EMBEDDED",
                "COMPLETED",
                "FAILED",
                name="ingestionstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("ingestion_error", sa.Text(), nullable=True),
        sa.Column("ingestion_task_id", sa.String(length=128), nullable=True),
        sa.Column("ingestion_attempts", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("char_length(title) > 0", name=op.f("ck_documents_title_not_empty")),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_documents_owner_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("content_sha256", name="uq_documents_content_sha256"),
    )
    op.create_index(op.f("ix_documents_created_at"), "documents", ["created_at"], unique=False)
    op.create_index(op.f("ix_documents_deleted_at"), "documents", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_documents_doi"), "documents", ["doi"], unique=False)
    op.create_index(
        "ix_documents_filters",
        "documents",
        ["access_level", "research_area", "document_type", "publication_date"],
        unique=False,
    )
    op.create_index(op.f("ix_documents_owner_id"), "documents", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_documents_publication_date"), "documents", ["publication_date"], unique=False
    )
    op.create_index(
        op.f("ix_documents_research_area"), "documents", ["research_area"], unique=False
    )
    op.create_index("ix_documents_status", "documents", ["ingestion_status"], unique=False)
    op.create_table(
        "experiments",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("methodology", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "RUNNING",
                "COMPLETED",
                "ABANDONED",
                name="experimentstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column(
            "access_level",
            sa.Enum(
                "PUBLIC", "INTERNAL", "RESTRICTED", name="accesslevel", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("model_system", sa.String(length=128), nullable=True),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("started_on", sa.Date(), nullable=True),
        sa.Column("completed_on", sa.Date(), nullable=True),
        sa.Column("lead_researcher", sa.String(length=255), nullable=True),
        sa.Column("compound_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["compound_id"],
            ["compounds.id"],
            name=op.f("fk_experiments_compound_id_compounds"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["research_topics.id"],
            name=op.f("fk_experiments_topic_id_research_topics"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiments")),
        sa.UniqueConstraint("code", name="uq_experiments_code"),
    )
    op.create_index(
        op.f("ix_experiments_access_level"), "experiments", ["access_level"], unique=False
    )
    op.create_index(
        op.f("ix_experiments_compound_id"), "experiments", ["compound_id"], unique=False
    )
    op.create_index(
        "ix_experiments_compound_id_status", "experiments", ["compound_id", "status"], unique=False
    )
    op.create_index(op.f("ix_experiments_created_at"), "experiments", ["created_at"], unique=False)
    op.create_index(op.f("ix_experiments_topic_id"), "experiments", ["topic_id"], unique=False)
    op.create_index(
        "ix_experiments_topic_id_started_on",
        "experiments",
        ["topic_id", "started_on"],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_index("ix_user_roles_role_id", "user_roles", ["role_id"], unique=False)
    op.create_table(
        "agent_messages",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "SYSTEM",
                "USER",
                "ASSISTANT",
                "TOOL",
                name="messagerole",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("node", sa.String(length=64), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_messages_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_messages")),
    )
    op.create_index(
        op.f("ix_agent_messages_created_at"), "agent_messages", ["created_at"], unique=False
    )
    op.create_index(
        "ix_agent_messages_run_id_sequence", "agent_messages", ["run_id", "sequence"], unique=True
    )
    op.create_table(
        "approval_requests",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_id", sa.Uuid(), nullable=True),
        sa.Column("decided_by_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_level", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "EXPIRED",
                name="approvalstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"],
            ["users.id"],
            name=op.f("fk_approval_requests_decided_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
            name=op.f("fk_approval_requests_requested_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_approval_requests_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_requests")),
    )
    op.create_index(
        op.f("ix_approval_requests_created_at"), "approval_requests", ["created_at"], unique=False
    )
    op.create_index("ix_approval_requests_run_id", "approval_requests", ["run_id"], unique=False)
    op.create_index(
        "ix_approval_requests_status_created_at",
        "approval_requests",
        ["status", "created_at"],
        unique=False,
    )
    op.create_table(
        "document_chunks",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=255), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "chunk_index >= 0", name=op.f("ck_document_chunks_chunk_index_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint(
            "document_id", "chunk_index", name="uq_document_chunks_document_id_chunk_index"
        ),
    )
    op.create_index(
        op.f("ix_document_chunks_created_at"), "document_chunks", ["created_at"], unique=False
    )
    op.create_index(
        "ix_document_chunks_document_id_chunk_index",
        "document_chunks",
        ["document_id", "chunk_index"],
        unique=False,
    )
    op.create_index(
        "ix_document_chunks_embedding_hnsw",
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "evaluation_results",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("agent_run_id", sa.Uuid(), nullable=True),
        sa.Column("run_label", sa.String(length=128), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("deterministic_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("judge_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("judge_reasoning", sa.Text(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("failures", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("tools_used", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("human_verdict", sa.String(length=16), nullable=True),
        sa.Column("human_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["agent_runs.id"],
            name=op.f("fk_evaluation_results_agent_run_id_agent_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["evaluation_cases.id"],
            name=op.f("fk_evaluation_results_case_id_evaluation_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_results")),
    )
    op.create_index(
        "ix_evaluation_results_case_id_created_at",
        "evaluation_results",
        ["case_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluation_results_created_at"), "evaluation_results", ["created_at"], unique=False
    )
    op.create_index(
        "ix_evaluation_results_run_label_created_at",
        "evaluation_results",
        ["run_label", "created_at"],
        unique=False,
    )
    op.create_table(
        "experiment_results",
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=128), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=64), nullable=True),
        sa.Column("p_value", sa.Float(), nullable=True),
        sa.Column("confidence_interval", sa.String(length=128), nullable=True),
        sa.Column(
            "evidence_strength",
            sa.Enum(
                "STRONG",
                "MODERATE",
                "WEAK",
                "INCONCLUSIVE",
                name="evidencestrength",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("conclusion", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "p_value IS NULL OR (p_value >= 0 AND p_value <= 1)",
            name=op.f("ck_experiment_results_p_value_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
            name=op.f("fk_experiment_results_experiment_id_experiments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_experiment_results")),
        sa.UniqueConstraint(
            "experiment_id", "metric_name", name="uq_experiment_results_experiment_id_metric_name"
        ),
    )
    op.create_index(
        op.f("ix_experiment_results_created_at"), "experiment_results", ["created_at"], unique=False
    )
    op.create_index(
        "ix_experiment_results_experiment_id", "experiment_results", ["experiment_id"], unique=False
    )
    op.create_table(
        "tool_audit_logs",
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "REQUESTED",
                "AUTHORIZED",
                "DENIED",
                "EXECUTED",
                "FAILED",
                "TIMEOUT",
                name="toolcallstatus",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column("denial_reason", sa.String(length=255), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_tool_audit_logs_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tool_audit_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_audit_logs")),
    )
    op.create_index(
        op.f("ix_tool_audit_logs_created_at"), "tool_audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_tool_audit_logs_run_id_created_at",
        "tool_audit_logs",
        ["run_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_tool_audit_logs_tool_name_status",
        "tool_audit_logs",
        ["tool_name", "status"],
        unique=False,
    )
    op.create_index(
        "ix_tool_audit_logs_user_id_created_at",
        "tool_audit_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_audit_logs_user_id_created_at", table_name="tool_audit_logs")
    op.drop_index("ix_tool_audit_logs_tool_name_status", table_name="tool_audit_logs")
    op.drop_index("ix_tool_audit_logs_run_id_created_at", table_name="tool_audit_logs")
    op.drop_index(op.f("ix_tool_audit_logs_created_at"), table_name="tool_audit_logs")
    op.drop_table("tool_audit_logs")
    op.drop_index("ix_experiment_results_experiment_id", table_name="experiment_results")
    op.drop_index(op.f("ix_experiment_results_created_at"), table_name="experiment_results")
    op.drop_table("experiment_results")
    op.drop_index("ix_evaluation_results_run_label_created_at", table_name="evaluation_results")
    op.drop_index(op.f("ix_evaluation_results_created_at"), table_name="evaluation_results")
    op.drop_index("ix_evaluation_results_case_id_created_at", table_name="evaluation_results")
    op.drop_table("evaluation_results")
    op.drop_index(
        "ix_document_chunks_embedding_hnsw",
        table_name="document_chunks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_document_chunks_document_id_chunk_index", table_name="document_chunks")
    op.drop_index(op.f("ix_document_chunks_created_at"), table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ix_approval_requests_status_created_at", table_name="approval_requests")
    op.drop_index("ix_approval_requests_run_id", table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_created_at"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index("ix_agent_messages_run_id_sequence", table_name="agent_messages")
    op.drop_index(op.f("ix_agent_messages_created_at"), table_name="agent_messages")
    op.drop_table("agent_messages")
    op.drop_index("ix_user_roles_role_id", table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index("ix_experiments_topic_id_started_on", table_name="experiments")
    op.drop_index(op.f("ix_experiments_topic_id"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_created_at"), table_name="experiments")
    op.drop_index("ix_experiments_compound_id_status", table_name="experiments")
    op.drop_index(op.f("ix_experiments_compound_id"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_access_level"), table_name="experiments")
    op.drop_table("experiments")
    op.drop_index("ix_documents_status", table_name="documents")
    op.drop_index(op.f("ix_documents_research_area"), table_name="documents")
    op.drop_index(op.f("ix_documents_publication_date"), table_name="documents")
    op.drop_index(op.f("ix_documents_owner_id"), table_name="documents")
    op.drop_index("ix_documents_filters", table_name="documents")
    op.drop_index(op.f("ix_documents_doi"), table_name="documents")
    op.drop_index(op.f("ix_documents_deleted_at"), table_name="documents")
    op.drop_index(op.f("ix_documents_created_at"), table_name="documents")
    op.drop_table("documents")
    op.drop_index("ix_clinical_trials_status_start_date", table_name="clinical_trials")
    op.drop_index(op.f("ix_clinical_trials_created_at"), table_name="clinical_trials")
    op.drop_index("ix_clinical_trials_condition_phase", table_name="clinical_trials")
    op.drop_index(op.f("ix_clinical_trials_condition"), table_name="clinical_trials")
    op.drop_index(op.f("ix_clinical_trials_compound_id"), table_name="clinical_trials")
    op.drop_table("clinical_trials")
    op.drop_index("ix_agent_runs_user_id_created_at", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_thread_id"), table_name="agent_runs")
    op.drop_index("ix_agent_runs_status_created_at", table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_created_at"), table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index("ix_users_active_email", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_created_at"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_research_topics_research_area"), table_name="research_topics")
    op.drop_index(op.f("ix_research_topics_created_at"), table_name="research_topics")
    op.drop_table("research_topics")
    op.drop_index("ix_evaluation_cases_suite_enabled", table_name="evaluation_cases")
    op.drop_index(op.f("ix_evaluation_cases_created_at"), table_name="evaluation_cases")
    op.drop_table("evaluation_cases")
    op.drop_index(op.f("ix_compounds_therapeutic_area"), table_name="compounds")
    op.drop_index("ix_compounds_name_area", table_name="compounds")
    op.drop_index(op.f("ix_compounds_name"), table_name="compounds")
    op.drop_index(op.f("ix_compounds_created_at"), table_name="compounds")
    op.drop_table("compounds")
    # ### end Alembic commands ###
